### ISSUE TITLE
EAWebkit.sln can't load projects

### ISSUE THREAD

**Issue by ArionTT** [kitsilanosoftware/EAWebKit#11]
I download the EAWebkit 15.4.2.0.0,and open the solution with Visual Studio 2017 and Visual Studio 2015. but VS tell me

"can't found import project “C:\packages\Framework\3.34.00\data\FrameworkMsbuild.tasks”"

, then all the project the solution included are loaded failed. What is the Framework ?
Did you meet this problem when you built EAWebkit.dll ?

**Comment by bobsummerwill** [comment]
Please read ... https://github.com/kitsilanosoftware/EAWebKit/blob/master/README-BUILD.txt

These SLNs were built 4 years ago and have not been maintained.  They will only work with Visual Studio 2010.

**Comment by bobsummerwill** [comment]
By the way, EASTL is the crown jewel of the open sourced EA technology which I rebundled for Github back in 2014:

- https://bobsummerwill.com/2014/06/25/ea-open-source-software/
- https://kitsilanosoftware.com/2014/07/31/fork-me-ea/

The crown jewel is EASTL, which has since been officially releases by EA and is now maintained by @rparolin at https://github.com/electronicarts/EASTL.   And hello, @swardle :-)

- https://bobsummerwill.com/2016/02/10/eastl-has-been-open-sourced-by-ea-for-real/

This stuff is 4 years old and dead.  Head over to https://github.com/electronicarts/EASTL!
